<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64;x86</Platforms>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LINQPad.Reference" Version="1.0.56" />
  </ItemGroup>

  <Target Name="CopyToLinqPad" AfterTargets="Build" Condition="'$(OS)' == 'Windows_NT'">
    <Exec Command="if not exist &quot;%LOCALAPPDATA%\LINQPad\Drivers\DataContext\NetCore\DatabricksDriver&quot; mkdir &quot;%LOCALAPPDATA%\LINQPad\Drivers\DataContext\NetCore\DatabricksDriver&quot; &amp; xcopy /Y /I &quot;$(TargetDir)*&quot; &quot;%LOCALAPPDATA%\LINQPad\Drivers\DataContext\NetCore\DatabricksDriver\&quot;" />
  </Target>
</Project>
